import { SiteNav } from "../SiteNav";
import { SiteFooter } from "../SiteFooter";

export default function Terms() {
  return (
    <>
      <SiteNav />
      <main className="legal-page">
        <div className="legal-card">
          <h1>Terms &amp; Conditions</h1>
          <p className="legal-updated">Last updated: 18th August 2026</p>

          <p>
            These terms govern your use of SquadScout AI (&quot;the app&quot;, &quot;we&quot;, &quot;us&quot;). By
            creating an account, you agree to them.
          </p>

          <h2>1. What SquadScout AI is</h2>
          <p>
            SquadScout AI is an independent, unofficial companion app for Fantasy Premier League (FPL). It reads
            publicly available data from Fantasy Premier League&apos;s own API and presents it alongside
            AI-generated suggestions.
          </p>
          <p>
            SquadScout AI is not affiliated with, endorsed by, sponsored by, or in any way officially connected with
            the Premier League, the Football Association, Fantasy Premier League, or any Premier League club.
            &quot;Fantasy Premier League,&quot; &quot;FPL,&quot; club names, and player names are the property of
            their respective owners, referenced here only to describe publicly available statistics.
          </p>
          <p>
            SquadScout AI does not make transfers, changes, or any action on your actual FPL team. It&apos;s a
            read-only dashboard and advisory tool — you make every change yourself on the official FPL site or app.
          </p>

          <h2>2. Eligibility and accounts</h2>
          <p>
            You must be at least 16 years old to create an account. You&apos;re responsible for keeping your login
            credentials secure and for anything that happens under your account. You must provide a real FPL manager
            ID that belongs to you (or that you have permission to track).
          </p>

          <h2>3. The AI-generated suggestions</h2>
          <p>
            Transfer, captain, and chip suggestions are generated by an AI system (the Anthropic Claude API), based
            only on the FPL data available to the app at the time — your squad, fixtures, prices, and public
            form/points statistics.
          </p>
          <ul>
            <li>
              These are informational suggestions, not guaranteed advice. The AI can be wrong, can miss context it
              wasn&apos;t given (like a manager&apos;s press conference or a very recent injury not yet reflected in
              FPL&apos;s own data), and its output should be treated as one input into your own decision, not an
              instruction to follow blindly.
            </li>
            <li>
              We make no guarantee about the accuracy, completeness, or outcome of any suggestion, and we are not
              responsible for any points, rank, or prize money lost as a result of following (or not following)
              them.
            </li>
          </ul>

          <h2>4. Availability</h2>
          <p>
            SquadScout AI is a free, personally-run project. We don&apos;t guarantee uptime, and the service may be
            slow, unavailable, or discontinued at any time, with or without notice — including permanently. Data
            shown may occasionally be delayed or stale (for example, if Fantasy Premier League&apos;s own servers
            are struggling around a deadline); we try to indicate this in the app when it happens.
          </p>

          <h2>5. Acceptable use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Attempt to access another user&apos;s account or data.</li>
            <li>Use automated tools to scrape or overload the app beyond normal personal use.</li>
            <li>Use the app for any unlawful purpose.</li>
            <li>Attempt to reverse-engineer, resell, or rebrand the service.</li>
          </ul>
          <p>We may suspend or delete accounts that breach these terms.</p>

          <h2>6. Your data</h2>
          <p>
            See our <a href="/privacy">Privacy Policy</a> for what we collect and why. In short: we store your
            email, FPL manager ID, league IDs, and the squad/points/AI data needed to run your dashboard, and we
            don&apos;t sell or advertise with it.
          </p>

          <h2>7. Intellectual property</h2>
          <ul>
            <li>
              Player photographs shown in the app are sourced from, and remain the property of, the Premier League /
              their respective rights holders, used here for informational display of publicly available player
              data.
            </li>
            <li>Player and club names, statistics, and fixture data originate from Fantasy Premier League&apos;s public API.</li>
            <li>The SquadScout AI name, logo, and app design are our own and may not be reused without permission.</li>
          </ul>

          <h2>8. Limitation of liability</h2>
          <p>
            To the fullest extent permitted by law, SquadScout AI is provided &quot;as is,&quot; without warranties
            of any kind. We are not liable for any indirect, incidental, or consequential loss arising from your use
            of the app, including loss of FPL points, rank, or any associated prize money, whether from inaccurate
            data, a bug, downtime, or an AI-generated suggestion.
          </p>
          <p>Nothing in these terms limits liability where it would be unlawful to do so.</p>

          <h2>9. Termination</h2>
          <p>
            You can delete your account at any time via Settings. We may suspend or terminate accounts that breach
            these terms, or discontinue the service entirely, at our discretion.
          </p>

          <h2>10. Changes to these terms</h2>
          <p>
            We may update these terms as the app evolves. Continued use after an update means you accept the revised
            terms. Material changes will be reflected here with an updated date.
          </p>

          <h2>11. Governing law</h2>
          <p>These terms are governed by the laws of Scotland / England and Wales.</p>

          <h2>12. AI disclosure</h2>
          <p>
            SquadScout AI uses Anthropic&apos;s Claude AI to generate transfer, captain, and chip suggestions, based
            on your squad and publicly available Fantasy Premier League data. These suggestions are AI-generated and
            may be incomplete or incorrect — always use your own judgement before making changes to your FPL team.
          </p>

          <h2>13. Contact</h2>
          <p>
            Questions about these terms: <a href="mailto:contactus@squadscoutai.com">contactus@squadscoutai.com</a>
          </p>
        </div>
      </main>
      <SiteFooter />
    </>
  );
}
